version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST = db
      - DB_NAME = postgres
      - DB_USER = postgres
      - DB_PASS = postgres
    depends_on:
      - db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A consumerAffairs worker -l info
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
      - app